onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /four_onebitadder_dualrail_top/Cin_0
add wave -noupdate /four_onebitadder_dualrail_top/Cin_1
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Cin_ack
add wave -noupdate /four_onebitadder_dualrail_top/X0_0
add wave -noupdate /four_onebitadder_dualrail_top/X0_1
add wave -noupdate /four_onebitadder_dualrail_top/X0_ack
add wave -noupdate /four_onebitadder_dualrail_top/Y0_0
add wave -noupdate /four_onebitadder_dualrail_top/Y0_1
add wave -noupdate /four_onebitadder_dualrail_top/Y0_ack
add wave -noupdate /four_onebitadder_dualrail_top/X1_0
add wave -noupdate /four_onebitadder_dualrail_top/X1_1
add wave -noupdate /four_onebitadder_dualrail_top/X1_ack
add wave -noupdate /four_onebitadder_dualrail_top/Y1_0
add wave -noupdate /four_onebitadder_dualrail_top/Y1_1
add wave -noupdate /four_onebitadder_dualrail_top/Y1_ack
add wave -noupdate /four_onebitadder_dualrail_top/X2_0
add wave -noupdate /four_onebitadder_dualrail_top/X2_1
add wave -noupdate /four_onebitadder_dualrail_top/X2_ack
add wave -noupdate /four_onebitadder_dualrail_top/Y2_0
add wave -noupdate /four_onebitadder_dualrail_top/Y2_1
add wave -noupdate /four_onebitadder_dualrail_top/Y2_ack
add wave -noupdate /four_onebitadder_dualrail_top/X3_0
add wave -noupdate /four_onebitadder_dualrail_top/X3_1
add wave -noupdate /four_onebitadder_dualrail_top/X3_ack
add wave -noupdate /four_onebitadder_dualrail_top/Y3_0
add wave -noupdate /four_onebitadder_dualrail_top/Y3_1
add wave -noupdate /four_onebitadder_dualrail_top/Y3_ack
add wave -noupdate /four_onebitadder_dualrail_top/Sum0_0
add wave -noupdate /four_onebitadder_dualrail_top/Sum0_1
add wave -noupdate /four_onebitadder_dualrail_top/Sum1_0
add wave -noupdate /four_onebitadder_dualrail_top/Sum1_1
add wave -noupdate /four_onebitadder_dualrail_top/Sum2_0
add wave -noupdate /four_onebitadder_dualrail_top/Sum2_1
add wave -noupdate /four_onebitadder_dualrail_top/Sum3_0
add wave -noupdate /four_onebitadder_dualrail_top/Sum3_1
add wave -noupdate /four_onebitadder_dualrail_top/Cout0_0
add wave -noupdate /four_onebitadder_dualrail_top/Cout0_1
add wave -noupdate /four_onebitadder_dualrail_top/Cout1_0
add wave -noupdate /four_onebitadder_dualrail_top/Cout1_1
add wave -noupdate /four_onebitadder_dualrail_top/Cout2_0
add wave -noupdate /four_onebitadder_dualrail_top/Cout2_1
add wave -noupdate /four_onebitadder_dualrail_top/Cout_0
add wave -noupdate /four_onebitadder_dualrail_top/Cout_1
add wave -noupdate /four_onebitadder_dualrail_top/Cin0_ack
add wave -noupdate /four_onebitadder_dualrail_top/Cin1_ack
add wave -noupdate /four_onebitadder_dualrail_top/Cin2_ack
add wave -noupdate /four_onebitadder_dualrail_top/Cin3_ack
add wave -noupdate /four_onebitadder_dualrail_top/Sum0_ack
add wave -noupdate /four_onebitadder_dualrail_top/Sum1_ack
add wave -noupdate /four_onebitadder_dualrail_top/Sum2_ack
add wave -noupdate /four_onebitadder_dualrail_top/Sum3_ack
add wave -noupdate /four_onebitadder_dualrail_top/Cout0_ack
add wave -noupdate /four_onebitadder_dualrail_top/Cout1_ack
add wave -noupdate /four_onebitadder_dualrail_top/Cout2_ack
add wave -noupdate /four_onebitadder_dualrail_top/Cout3_ack
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/X0_0
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/X0_1
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/X1_0
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/X1_1
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/X2_0
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/X2_1
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/X3_0
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/X3_1
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Y0_0
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Y0_1
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Y1_0
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Y1_1
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Y2_0
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Y2_1
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Y3_0
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Y3_1
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Cin_0
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Cin_1
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Sum0_0
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Sum0_1
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Sum0_ack
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Sum1_0
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Sum1_1
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Sum1_ack
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Sum2_0
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Sum2_1
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Sum2_ack
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Sum3_0
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Sum3_1
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Sum3_ack
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Cout_0
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Cout_1
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Cout_ack
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/X0_ack
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/X1_ack
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/X2_ack
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/X3_ack
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Y0_ack
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Y1_ack
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Y2_ack
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/Y3_ack
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/a
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/b
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/c
add wave -noupdate /four_onebitadder_dualrail_top/adder_env/temp
add wave -noupdate /four_onebitadder_dualrail_top/adder1/X_0
add wave -noupdate /four_onebitadder_dualrail_top/adder1/X_1
add wave -noupdate /four_onebitadder_dualrail_top/adder1/Y_0
add wave -noupdate /four_onebitadder_dualrail_top/adder1/Y_1
add wave -noupdate /four_onebitadder_dualrail_top/adder1/Cin_0
add wave -noupdate /four_onebitadder_dualrail_top/adder1/Cin_1
add wave -noupdate /four_onebitadder_dualrail_top/adder1/Sum_0
add wave -noupdate /four_onebitadder_dualrail_top/adder1/Sum_1
add wave -noupdate /four_onebitadder_dualrail_top/adder1/Cout_0
add wave -noupdate /four_onebitadder_dualrail_top/adder1/Cout_1
add wave -noupdate /four_onebitadder_dualrail_top/adder1/X_ack
add wave -noupdate /four_onebitadder_dualrail_top/adder1/Y_ack
add wave -noupdate /four_onebitadder_dualrail_top/adder1/Cin_ack
add wave -noupdate /four_onebitadder_dualrail_top/adder1/Sum_ack
add wave -noupdate /four_onebitadder_dualrail_top/adder1/Cout_ack
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {17 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 322
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {109 ns} {332 ns}
